version: '3.8'

services:
  frontend:
    image: frontend
    container_name: cost_optimizer_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080

  backend:
    image: backend
    container_name: cost_optimizer_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cost_optimizer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=your_password
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=your_password
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.9.0
    container_name: neo4j_db
    restart: always
    environment:
      NEO4J_AUTH: neo4j/your_password
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt Protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
